### ISSUE TITLE
createNewUser callback is never called

### ISSUE THREAD

**Issue by MichaelTaylor3D** [SaintDako/node-email-verification#13] opened 2015-10-23 01:54 UTC
callback is never called, any idea on what could be causing this? Am I missing a setting?

       var newUser = new User({
          name: req.body.name,
          password: md5(req.body.password),
          email: req.body.email
        });

        nev.createTempUser(newUser, function(err, newTempUser) {
          if(newTempUser) {
            nev.registerTempUser(newTempUser, function(err) {
              res.json({sucess: true, message: 'An email has been sent for verification'});
            });
          } else {
            res.json({success: false, message: 'This username is awaiting verification, please check your email'});
          }
        });

**Comment by SaintDako** [comment] 2015-10-23 03:01
does the express example work for you?

**Comment by MichaelTaylor3D** [comment] 2015-10-23 18:19
yes the express example does work,

Ive continued to debug, I found that the issue is on line 141 of the email verification modules index.js.

The callback in 

``` options.tempUserModel.findOne(query, function(err, existingUser) ```

is whats never being called. I have verified that options.tempUserModel returns a valid model, and I have verified that query[options.emailFieldName] contains a valid email.

But it seems to never call the query callback. Ive verified the database is running.

It seems that I must be missing something in my setup, but Ive combed over the example express and cant find any missing pieces.

Based on the info that I gave does anything come to mind?

**Comment by MichaelTaylor3D** [comment] 2015-10-23 18:23
Ive noticed that the github version has a async dependency and the version I got from npm does not. Do you think this could be related?

**Comment by frankcash** [comment] 2015-10-23 18:34
What is the version # of the package you got from NPM?

**Comment by MichaelTaylor3D** [comment] 2015-10-23 18:40
0.1.9

**Comment by frankcash** [comment] 2015-10-23 18:43
@SaintDako can you push the latest version to NPM>?

**Comment by SaintDako** [comment] 2015-10-23 18:45
Will do. Currently at my university convocation. Kill me.

**Comment by SaintDako** [comment] 2015-10-23 23:08
was pushed to npm just now

**Comment by frankcash** [comment] 2015-10-24 13:39
@MichaelTaylor3D do you know if using the newest version fixed your issue?

**Comment by MichaelTaylor3D** [comment] 2015-10-24 18:52
Im still testing it, doing my best to make sure Im not missing something obvious. It still cant get past line 161 in the new version (which was line 141 in the old)
```options.tempUserModel.findOne(query, function(err, existingUser) { ... }```
The callback in this function never gets invoked. Console logged out the query variable to be 
```{ email: 'test@test.com' }```

**Comment by MichaelTaylor3D** [comment] 2015-10-24 19:19
just noticed, that the express example uses mongoose 3.9.7, and Im using monoose 4.2.0 and I noticed that there findOne implementation seems to be different. Im currently trying to get 3.9.7 implemented in my project. I have a feeling this may be the cause of the issue.

**Comment by SaintDako** [comment] 2015-10-24 19:29
If the temp user model is being created with nev, then nev's function calls
should be using the version of Mongoose that is specified in its
package.json (3.8.19). Then again, the ^ (caret) may be messing with
things. I'll try an example today

just noticed, that the express example uses mongoose 3.9.7, and Im using
monoose 4.2.0 and I noticed that there findOne implementation seems to be
different. Im currently trying to get 3.9.7 implemented in my project. I
have a feeling this may be the cause of the issue.

—
Reply to this email directly or view it on GitHub
<https://github.com/SaintDako/node-email-verification/issues/13#issuecomment-150842160>
.

**Comment by MichaelTaylor3D** [comment] 2015-10-24 20:08
I got it to work! well sortof, the callback is finally being called, there is a MongooseError.ValidationError, but its possible that this could be my code.

I got it to work by pulling your nev code out of node modules and into my main project. Its possible that it worked because its now sharing the main mongoose installation.

**Comment by MichaelTaylor3D** [comment] 2015-10-24 20:20
yep, validation error was my problem, I set field username to be unique, but it seems when you create the temp model something happens that makes it not so unique. But other then that, its now working.

**Comment by SaintDako** [comment] 2015-10-25 16:21
I think I am now, actually. it seems that npm has changed the way `node_modules` works. if I'm not entirely crazy, I believe that the dependencies for each package were located inside the package's folder, e.g.

```
| yourapp.js
| node_modules/
|-- mongoose/
|-- |-- node_modules/
|-- email-verification
|-- |-- node_modules/
```

buuuut it seems that there are no inner dependencies, because `require` will look in parent directories. thus, if your app is using the newest version of Mongoose which apparently has breaking changes to the API, then it will not work. I should specify a 3.x version specifically for this version of NEV, and then later I can update NEV to suit Mongoose 4.x.

**Comment by SaintDako** [comment] 2015-10-25 16:48
never mind, running `npm install --save email-verification` will install a 3.x version of Mongoose, but if your app also depends on Mongoose and you run `npm install --save mongoose`, you'll get the 4.x version. also, I believe Mongoose 3.9.x and 4.x are unstable, where as 3.8.x is the stable version, so it's presumably best to stick with the 3.8.x versions for now.

**Comment by SaintDako** [comment] 2015-10-26 01:25
**I fixed the issue**

NEV has `require('mongoose')`, so you were right, @MichaelTaylor3D, sorta - NEV requires the app-wide version of Mongoose. this issue can be fixed by exporting all of `index.js` as a function and passing in `mongoose` as a parameter:

```
// require statements ...
module.exports = function(mongoose) {

// rest of index.js...

return {
  options: ... ,
  ...
}

}
```

this can be done easily and I'll do it in a bit

**Comment by MichaelTaylor3D** [comment] 2015-10-26 19:19
awesome, thanks for looking into it!

**Closed** 2015-10-29 21:13 UTC
